### ISSUE TITLE
How to put day of week like Moday, Tuesday, Wednesday to date format?

### ISSUE THREAD

**Issue by DrFrankatron** [Snow-Developer/StatsSB#4]
How to put day of week like Monday, Tuesday, Wednesday to date format? The scoreboard that I have is this:

```
# Scoreboard Settings, Self explanatory.
Scoreboard: 
   enabled: true
   toggledByDefault: true
   resetScoreboardToggleOnJoin: false
   toggleSBMessageOn: '&7Scoreboard has been Toggled &aOn'
   toggleSBMessageOff: '&7Scoreboard has been Toggled &cOff'
   dateTimeZone: CET
   dateFormat: dd MMMM yyyy HH:mm:ss
   Economy: 
      enabled: false
   title: '&3Global Player Info:'
   layout: 
   - '&7%date%'
   - '%blank-1%'
   - '&fUser: &3%user%'
   - '&fPlacement: &3%kills_rank%'
   - '&fKills: &3%kills%'
   - '&fDeaths: &3%deaths%'
   - '%blank-2%'
   - '&7&l&m-------------'
   ```
   
   I tried 'W' and 'w' and 'D', but nothing happened... how can i solve it for retrieving it the correct day of a weeb?
